name: keyboard_insets_platform_interface
description: Platform interface for the keyboard_insets plugin.
version: 1.0.0
homepage: "github.com/urbi/keyboard_insets"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0