name: keyboard_insets
description: A Flutter plugin that provides real-time keyboard height and visibility state across platforms.
version: 0.1.0

repository: https://github.com/urbi/keyboard_insets
homepage: https://github.com/urbi/keyboard_insets

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  keyboard_insets_platform_interface: ^1.0.0
  keyboard_insets_mobile: ^0.1.0
  keyboard_insets_web: ^0.1.0

flutter:
  plugin:
    platforms:
      android:
        default_package: keyboard_insets_mobile
      ios:
        default_package: keyboard_insets_mobile
      web:
        default_package: keyboard_insets_web
