name: keyboard_insets_web
description: "Web implementation of keyboard_insets"
version: 0.1.1

repository: https://github.com/urbi-ae/keyboard_insets
homepage: https://github.com/urbi-ae/keyboard_insets

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: '>=3.3.0'
  

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  keyboard_insets_platform_interface: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: KeyboardInsetsWeb
        fileName: keyboard_insets_web.dart